// <auto-generated />
using System;
using Jaryway.DynamicSpace.DynamicWebApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jaryway.DynamicSpace.DynamicWebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240718103148_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("Jaryway.DynamicSpace.DynamicWebApi.Models.DynamicClass", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityProperties")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityProperties_")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JSON")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Published")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DynamicClasses");
                });

            modelBuilder.Entity("Jaryway.DynamicSpace.DynamicWebApi.Models.MigrationEntry", b =>
                {
                    b.Property<string>("MigrationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("MigrationId");

                    b.ToTable("MigrationEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
